candlestick_patterns = {
	'CDL2CROWS':'Two Crows',
	'CDL3BLACKCROWS':'Three Black Crows',
	'CDL3INSIDE':'Three Inside Up/Down',
	'CDL3LINESTRIKE':'Three-Line Strike',
	'CDL3OUTSIDE':'Three Outside Up/Down',
	'CDL3STARSINSOUTH':'Three Stars In The South',
	'CDL3WHITESOLDIERS':'Three Advancing White Soldiers',
	'CDLABANDONEDBABY':'Abandoned Baby',
	'CDLADVANCEBLOCK':'Advance Block',
	'CDLBELTHOLD':'Belt-hold',
	'CDLBREAKAWAY':'Breakaway',
	'CDLCLOSINGMARUBOZU':'Closing Marubozu',
	'CDLCONCEALBABYSWALL':'Concealing Baby Swallow',
	'CDLCOUNTERATTACK':'Counterattack',
	'CDLDARKCLOUDCOVER':'Dark Cloud Cover',
	'CDLDOJI':'Doji',
	'CDLDOJISTAR':'Doji Star',
	'CDLDRAGONFLYDOJI':'Dragonfly Doji',
	'CDLENGULFING':'Engulfing Pattern',
	'CDLEVENINGDOJISTAR':'Evening Doji Star',
	'CDLEVENINGSTAR':'Evening Star',
	'CDLGAPSIDESIDEWHITE':'Up/Down-gap side-by-side white lines',
	'CDLGRAVESTONEDOJI':'Gravestone Doji',
	'CDLHAMMER':'Hammer',
	'CDLHANGINGMAN':'Hanging Man',
	'CDLHARAMI':'Harami Pattern',
	'CDLHARAMICROSS':'Harami Cross Pattern',
	'CDLHIGHWAVE':'High-Wave Candle',
	'CDLHIKKAKE':'Hikkake Pattern',
	'CDLHIKKAKEMOD':'Modified Hikkake Pattern',
	'CDLHOMINGPIGEON':'Homing Pigeon',
	'CDLIDENTICAL3CROWS':'Identical Three Crows',
	'CDLINNECK':'In-Neck Pattern',
	'CDLINVERTEDHAMMER':'Inverted Hammer',
	'CDLKICKING':'Kicking',
	'CDLKICKINGBYLENGTH':'Kicking - bull/bear determined by the longer marubozu',
	'CDLLADDERBOTTOM':'Ladder Bottom',
	'CDLLONGLEGGEDDOJI':'Long Legged Doji',
	'CDLLONGLINE':'Long Line Candle',
	'CDLMARUBOZU':'Marubozu',
	'CDLMATCHINGLOW':'Matching Low',
	'CDLMATHOLD':'Mat Hold',
	'CDLMORNINGDOJISTAR':'Morning Doji Star',
	'CDLMORNINGSTAR':'Morning Star',
	'CDLONNECK':'On-Neck Pattern',
	'CDLPIERCING':'Piercing Pattern',
	'CDLRICKSHAWMAN':'Rickshaw Man',
	'CDLRISEFALL3METHODS':'Rising/Falling Three Methods',
	'CDLSEPARATINGLINES':'Separating Lines',
	'CDLSHOOTINGSTAR':'Shooting Star',
	'CDLSHORTLINE':'Short Line Candle',
	'CDLSPINNINGTOP':'Spinning Top',
	'CDLSTALLEDPATTERN':'Stalled Pattern',
	'CDLSTICKSANDWICH':'Stick Sandwich',
	'CDLTAKURI':'Takuri (Dragonfly Doji with very long lower shadow)',
	'CDLTASUKIGAP':'Tasuki Gap',
	'CDLTHRUSTING':'Thrusting Pattern',
	'CDLTRISTAR':'Tristar Pattern',
	'CDLUNIQUE3RIVER':'Unique 3 River',
	'CDLUPSIDEGAP2CROWS':'Upside Gap Two Crows',
	'CDLXSIDEGAP3METHODS':'Upside/Downside Gap Three Methods'
}


values = ['Two Crows', 'Three Black Crows', 'Three Inside Up/Down', 
		'Three-Line Strike', 'Three Outside Up/Down', 'Three Stars In The South', 
		'Three Advancing White Soldiers', 'Abandoned Baby', 'Advance Block', 'Belt-hold', 'Breakaway', 'Closing Marubozu', 'Concealing Baby Swallow', 'Counterattack', 'Dark Cloud Cover', 'Doji', 'Doji Star', 'Dragonfly Doji', 'Engulfing Pattern', 'Evening Doji Star', 'Evening Star', 'Up/Down-gap side-by-side white lines', 'Gravestone Doji', 'Hammer', 'Hanging Man', 'Harami Pattern', 'Harami Cross Pattern', 'High-Wave Candle', 'Hikkake Pattern', 'Modified Hikkake Pattern', 'Homing Pigeon', 'Identical Three Crows', 'In-Neck Pattern', 'Inverted Hammer', 'Kicking', 'Kicking - bull/bear determined by the longer marubozu', 'Ladder Bottom', 'Long Legged Doji', 'Long Line Candle', 'Marubozu', 'Matching Low', 'Mat Hold', 'Morning Doji Star', 'Morning Star', 'On-Neck Pattern', 'Piercing Pattern', 'Rickshaw Man', 'Rising/Falling Three Methods', 'Separating Lines', 'Shooting Star', 'Short Line Candle', 'Spinning Top', 'Stalled Pattern', 'Stick Sandwich', 'Takuri (Dragonfly Doji with very long lower shadow)', 'Tasuki Gap', 'Thrusting Pattern', 'Tristar Pattern', 'Unique 3 River', 'Upside Gap Two Crows', 'Upside/Downside Gap Three Methods']